homework3: user_interface.o database.o
	gcc -o homework3 user_interface.o database.c

user_interface.o: user_interface.c database.h
	gcc -ansi -pedantic-errors -Wall -c user_interface.c 

database.o: database.c record.h
	gcc -ansi -pedantic-errors -Wall -c database.c